<?php
/*------------------------------------------------------------------------
 # SM Tab Listing - Version 1.0
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$smarthelper = Mage::helper('tablisting/utils');
$options  = $this->getConfigObject();
$maxtitle = $options->item_title_max_characs;
$post     = Mage::app()->getRequest()->getPost();
$is_ajax  = $post['is_ajax'];
$cat_id   = $post['tab_cat_id'];
$order_id = $params['order_id'];
$count    = $post['ajax_tablisting_start'];

if( $is_ajax ){ 
	$type     =  $post['data_type'];
	if( $type == 'order' ){
		$child_items = $this->getProductsOrder($order_id);
	} else {
		$child_items = $this->getProducts($cat_id);
	}
}
if( !empty($child_items) ) { 
	if( $is_ajax ){
		$k = $count;
	} else {
		$k = 0;
	}
	foreach( $child_items  as $item ){ $k++; 
		$_product = Mage::getModel('catalog/product')->load($item->id);
	?>
	<div class="respl-item">
		<div class="item-inner">
			<div class="item-image">
				<a class="rspl-image" href="<?php echo $item->link ?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true" title="<?php echo $item->title?>" >
					<img src="<?php echo $item->image;?>"  alt="<?php echo $item->title;?>" />
				</a>
			</div>
			<?php if( $options->item_title_display == 1 || $options->item_desc_display == 1 || $options->item_price_disp == 1 || $options->item_review_disp == 1 || $options->item_cart_disp == 1 || $options->item_wishlist_disp == 1 || $options->item_compare_disp == 1 ){?>
			<div class="item-info">
				<?php if( $options->item_title_display == 1 ){?>
				<div class="item-title ">
					<a href="<?php echo $item->link ?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true"  title="<?php echo $item->title?>" >
						<?php echo $item->title; ?>
					</a>
				</div>
				<?php }?>
				<?php if( $options->item_desc_display == 1 ) {?>
				<div class="item-desc">
					<?php echo $item->description; ?>
				</div>
				<?php }?>
				<?php if( $options->item_price_disp == 1 ) {	?>
				<div class="item-price">
					  <?php echo $item->price_html; ?>
				</div>
				<?php }?>
				<?php if( $options->item_review_disp == 1 ) {?>
				<div class="item-review">
					<?php echo $item->review_html; ?>
				</div>
				<?php }?>
				<?php if( $options->item_cart_disp == 1 ) {?>
				<?php if($_product->isSaleable()){ ?>
				<div class="item-addcart">
					<a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
						<?php echo $this->__('Add to Cart') ?>
					</a>
				</div>
				<?php }else{ ?>
					<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>										
				<?php }}?>
	            <?php if ($this->helper('wishlist')->isAllow() && $options->item_wishlist_disp == 1 ) { ?>
	            <div class="item-wishlist">
	            	<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
	            </div>
	            <?php } ?>
	            <?php if( $options->item_compare_disp == 1 && $_compareUrl=$this->getAddToCompareUrl($_product)){ ?>
	            <div class="item-compare">
	            	<a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
	            </div>
	            <?php } ?>
            </div>
			<?php }?>
		</div>
	</div>
	<?php $clear = 'clr1';
	if ($k % 2 == 0) $clear .= ' clr2';
	if ($k % 3 == 0) $clear .= ' clr3';
	if ($k % 4 == 0) $clear .= ' clr4';
	if ($k % 5 == 0) $clear .= ' clr5';
	if ($k % 6 == 0) $clear .= ' clr6';
	?>
	<div class="<?php echo $clear; ?>"></div>
<?php }}?>
