<?php
//$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
 ?>
 <?php
 $subtotal = (Mage::helper('checkout/cart')->getQuote()->getSubtotal()) * 1.21;
 $shipping_cost = 3.45;
 if($subtotal > 35) $shipping_cost = 0.00;
 $cart_total =  $subtotal + $shipping_cost;
   ?>

<div class="mini-cart-layer">
	<?php if ($this->getIsNeedToDisplaySideBar()):?>
		<div class="top-cart">
    			<?php $_cartQty1 = Mage::getModel('checkout/cart')->getQuote()->getItemsQty();
                $_cartQty = (int)$_cartQty1;
                ?>
			<?php if ($_cartQty > 0): ?>
				<?php $_myCart = $this->__('%s', $_cartQty) ?>
			<?php else: ?>
				<?php $_myCart = $this->__('0') ?>
			<?php endif ?>

			<?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()):?>
				<div class="block-title no-items">
					<ul class="links cart-link">
						<li ><a href="<?php echo $this->getUrl('checkout/cart'); ?>" rel="nofollow"><?php echo $_myCart ?></a></li>
					</ul>
				</div>
			<?php else:?>
				<div class="block-title<?php if(!$_cartQty) { echo (' no-items'); } ?>">
                    <div class="destop_cart">
                        <span id="cartHeader">
                            <span class="cart_counter"><?php echo $_myCart ?></span><span id="car_arrow">&nbsp;</span>
                        </span>
                    </div>
                    <div class="mobile_cart">
                        <span onclick="window.location='<?php echo $this->getUrl('checkout/cart'); ?>'" id="cartHeader">
                            <span class="cart_counter"><?php echo $_myCart ?></span><span id="car_arrow">&nbsp;</span>
                        </span>
                    </div>

				</div>
				<div id="topCartContent" class="block-content" style="display:none">
					<div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
						<?php $_items = $this->getRecentItems() ?>
						<?php if(count($_items)): ?>
							<p class="block-subtitle">
								<span onclick="toggleTopCart();" class="close-btn"><?php echo $this->__('Close'); ?></span>
								<?php echo $this->__('basket') ?>
							</p>
							<ol id="mini-cart" class="mini-products-list">
								<?php foreach($_items as $_item): ?>
									<?php echo $this->getItemHtml($_item) ?>
								<?php endforeach; ?>
							</ol>
							<script type="text/javascript">decorateList('mini-cart', 'none-recursive')</script>
						<?php else: ?>
							<p class="block-subtitle">
								<span onclick="toggleTopCart()" class="close-btn"><?php echo $this->__('Close'); ?></span>
									<?php echo $this->__('Recently added item(s)') ?>
							</p>
							<p class="cart-empty">
								<?php echo $this->__('You have no items in your shopping cart.') ?>
							</p>
						<?php endif ?>
                        	<?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="total_right">
                            <div class="clearfix">
                                <p><?php echo $this->__('Shipping costs');?><span class="ship"><?php echo '€ ' . number_format($shipping_cost, 2, ',', '.'); ?></span></p>
                            </div>
                            <div class="subtotal">
                                <?php if ($this->canApplyMsrp()): ?>
                                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                                <?php else: ?>
                                    <span class="label"><?php echo $this->__('Total amount') ?></span><span class="totaalbedrag"><?php echo '€ ' . number_format($cart_total, 2, ',', '.'); ?></span>
                                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                     </div>
					<div class="clear"></div>
							<div class="actions clearfix">
								<a href="<?php echo $this->getUrl('checkout/cart'); ?>" rel="nofollow"><?php echo $this->__('Go to Shopping Cart') ?></a>
								<button class="button" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><?php echo $this->__('order') ?></span></button>
							</div>
						<?php endif ?>
					</div>
				</div>
			<?php endif;?>
		</div>
	<?php endif;?>
</div>
