<?php $storePhone = Mage::getStoreConfig('general/store_information/phone'); ?>
<div class="block checkout-side">
	<ul>
		<li>
			<h2><?php echo $this->__('Hulp nodig tijdens '); ?><br><?php echo $this->__('het afrekenen?'); ?></h4>
			<p class="green">Tel: <?php echo $storePhone; ?></p>
		</li>
		<li>
			<a href="https://www.qshops.org/webshop/view/knipengoshop-nl" target="_blank"><img src="/media/wysiwyg/qshops-logo.png" alt=""></a></li>
		<li>
			<p><span class="bold"><?php echo $this->__('Producten op voorraad?'); ?></span></br><?php echo $this->__('Voor 21:00 besteld, morgen in huis!'); ?></span></p>
		</li>
		<li>
			<img src="/media/wysiwyg/product_paymentimage.jpg" alt="">
		</li>
	</ul>
	<div class="trustpilot-widget trustpilot_cart" data-locale="nl-NL" data-template-id="539ad0ffdec7e10e686debd7" data-businessunit-id="5481d6f000006400057bf727" data-style-height="350px" data-style-width="100%" data-theme="light" data-stars="1,2,3,4,5">
		<a href="https://nl.trustpilot.com/review/www.knipengoshop.nl" target="_blank">Trustpilot</a>
	</div>
</div>