<?php
/**
 * @category   design_default
 * @package    PayNL_Ideal
 * @copyright  Copyright (c) 2009 TinTel
 */
?>
<?php $_code=$this->getMethodCode() ?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_ideal_bank_id"><?php echo $this->__('BankCode') ?> <span class="required">*</span></label><br/>
                <input type="text" name="payment[giropay_bank_id]" class="required-entry" />
            </div>
        </li>
    </ul>

</fieldset>