<?php
$category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$categoriesid = array();
$categories = $category->getCollection()
        ->addAttributeToSelect(array('name', 'thumbnail','description'))
        ->addAttributeToFilter('is_active', 1)
        ->addIdFilter($category->getChildren());
     
    
   //$this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper');

    //print_r($category);
    $storeId = Mage::app()->getStore()->getId();

   /* $products =array();
    $cats = Mage::getModel('catalog/category')->load($category->getId())->getChildren();
    $catIds = explode(',',$cats);
   // print_r($catIds);
    if($catIds[0] !=''){
        if(count($products)==0){
            foreach($catIds as $sub_1){
                echo $sub_1.'aaa';
                 $products = Mage::getModel('catalog/product')->load($sub_1)->getProductCollection();
                 $sub_1_cat = Mage::getModel('catalog/category')->load($sub_1)->getChildren();
                 $catIds_2 = explode(',',$sub_1_cat);
                 if($catIds_2[0] !=''){
                    if(count($products)==0){

                        foreach($catIds_2 as $sub_2){
                            echo $sub_2.'bbb';
                          $products = Mage::getModel('catalog/product')->load($sub_2)->getProductCollection();
                          $sub_2_cat = Mage::getModel('catalog/category')->load($sub_2)->getChildren();
                          $catIds_3 = explode(',',$sub_2_cat);

                            if($catIds_3[0] !=''){
                                    if(count($products)==0){
                                        foreach($catIds_3 as $sub_3){
                                            echo $sub_3.'ccc';
                                          $products = Mage::getModel('catalog/product')->load($sub_3)->getProductCollection();
                                          $sub_3_cat = Mage::getModel('catalog/category')->load($sub_3)->getChildren();
                                          }
                                    }
                                 }
                          }
                    }
                 }
             }
        }
    } */


    $_main_cat_id = $category->getId();

    $all_subcats = implode(',',find_child($_main_cat_id));

    function find_child($cat_id)
    {
        $cat = Mage::getModel('catalog/category')->load($cat_id);
        if($subcats = $cat->getChildren())
        {
            $subcats_arr = explode(',' , $subcats);
            $a[] = $cat_id;
            foreach($subcats_arr as $x=>$v):
                $a =  array_merge($a , find_child($v));
            endforeach;
            return $a;
        }
        else
            return array($cat_id);
    }


    $collection = mage::getModel('catalog/product')->getCollection()
        ->joinField('category_id',
            'catalog/category_product',
            'category_id',
            'product_id=entity_id',
            null,
            'left')
        ->addAttributeToFilter('category_id', array('in' => explode(',' , $all_subcats)));
    $collection->getSelect()->group('e.entity_id');

    $product_ids =array();

    $i=1;
    foreach($collection as $_product):

        $summaryData = Mage::getModel('review/review_summary')
            ->setStoreId($storeId)
            ->load($_product->getId());

        if ($summaryData['rating_summary']){
             if($i <= 5){
            $product_ids[] = $_product->getId();
             $i++;
            }
        }

    endforeach;


  /* $products = Mage::getModel('catalog/category')->load(18)->getProductCollection();
    $i=1;
    foreach($products as $product){
        $product = Mage::getModel('catalog/product')->load($product->getId());
        $summaryData = Mage::getModel('review/review_summary')
        					->setStoreId($storeId)
        					->load($product->getId());

        if ($summaryData['rating_summary']!=''){
           // if($i <= 5){
            $product_ids[] = $product->getId();
           // $i++;
           // }
         }
    } */
    
    //$str_product_ids = implode(',',$product_ids);
    $str_product_ids = $product_ids;


    $reviewcollection = Mage::getModel('review/review')->getCollection()
        ->addStoreFilter(Mage::app()->getStore()->getId())
        ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
        ->addFieldToFilter('entity_id', Mage_Review_Model_Review::ENTITY_PRODUCT)
        ->addFieldToFilter('entity_pk_value', array('in' => $str_product_ids))
        ->setDateOrder()
        ->addRateVotes();
        
    
    
    $_items = $reviewcollection->getItems();  
    
    
?>

<ul id="top_level_cat" class="subcategories">
    <?php foreach ($categories as $category): ?>
        <li>
            <div class="product-title_bg">
                <h4 class="category_title"><a  href="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a></h4>
                <a href="<?php echo $category->getUrl() ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/category/'  . $category->getThumbnail() ?>" alt="<?php echo $this->htmlEscape($category->getName()) ?>" /></a>
            </div>
            <div class="category-description">
                <div class="category-description-inner">
                    
                    <p><?php echo $category->getDescription() ?></p>
                </div>
            </div>
                
        </li>
    <?php 
    $categoriesid[]=$category->getId;
    endforeach; ?>
</ul>
<div class="category_trustpilot_home">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('trustpilot_home')->toHtml(); ?>
</div>

<div class="review_bestselling clearfix">
<div class="review_bestselling_left">
<h3><?php echo $this->__('Beoordelingen');?></h3>
    <ul>
      <?php  foreach($_items as $_review):
          $rvproduct = Mage::getModel('catalog/product')->load($_review->getData('entity_pk_value'));
          $totalrv = 0;
          $_votes_t = $_review->getRatingVotes();
          if (count($_votes_t)):
              foreach ($_votes_t as $_vote_n):
                  $totalrv = $totalrv+$_vote_n->getValue();
              endforeach;
          endif;
    ?>
        <li class="clearfix">
            <div class="review_left">
                <img src="src="<?php  Mage::helper('catalog/image')->init($rvproduct, 'thumbnail');?>" />
                <span class="review_count"> <?php echo $totalrv; ?></span>
            </div>
            <div class="review_right">
                <h4><a href="<?php echo $this->getReviewUrl($_review->getId()) ?>">
                    <?php //echo $this->escapeHtml($_review->getTitle()) ?>
                    <?php echo $rvproduct->getName(); ?>
                </a> <span>volgens</span> <span class="author"><?php echo $this->__('Review by %s', $this->escapeHtml($_review->getNickname())) ?></span></h4>
                <p><?php echo nl2br($this->escapeHtml($_review->getDetail())) ?></p>
                <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>" class="redamore">lees meer</a>
            </div>
        </li>
<?php
      continue;
    endforeach;
               
?>  
        
        <li class="clearfix">
            <div class="review_left">
                <img src="<?php echo $this->getSkinUrl('images/review_small_img.jpg');?>" />
                <span class="review_count">10</span>
            </div>
            <div class="review_right">
                <h4>Goldwell Jam (200)gr <span>volgens</span> <span class="author">Jasmijn</span></h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis nunc sed purus suscipit, eget convallis magn</p>
                <a href="#" class="redamore">lees meer</a>
            </div>
        </li>
        <li class="clearfix">
            <div class="review_left">
                <img src="<?php echo $this->getSkinUrl('images/review_small_img.jpg');?>" />
                <span class="review_count">10</span>
            </div>
            <div class="review_right">
                <h4>Goldwell Jam (200)gr <span>volgens</span> <span class="author">Jasmijn</span></h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis nunc sed purus suscipit, eget convallis magn</p>
                <a href="#" class="redamore">lees meer</a>
            </div>
        </li>
        <li class="clearfix">
            <div class="review_left">
                <img src="<?php echo $this->getSkinUrl('images/review_small_img.jpg');?>" />
                <span class="review_count">10</span>
            </div>
            <div class="review_right">
                <h4>Goldwell Jam (200)gr <span>volgens</span> <span class="author">Jasmijn</span></h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis nunc sed purus suscipit, eget convallis magn</p>
                <a href="#" class="redamore">lees meer</a>
            </div>
        </li>
        <li class="clearfix">
            <div class="review_left">
                <img src="<?php echo $this->getSkinUrl('images/review_small_img.jpg');?>" />
                <span class="review_count">10</span>
            </div>
            <div class="review_right">
                <h4>Goldwell Jam (200)gr <span>volgens</span> <span class="author">Jasmijn</span></h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis nunc sed purus suscipit, eget convallis magn</p>
                <a href="#" class="redamore">lees meer</a>
            </div>
        </li>
    </ul>
<div class="review_block">
<?php 
$category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$category = Mage::getModel('catalog/category')->load($category_id);
$products = Mage::getModel('catalog/product')
    ->getCollection()
    ->addAttributeToSelect('*')
    ->addCategoryFilter($category)
    ->setOrder('price', 'ASC')
    ->load();
    
$counter=0; 
$proids = array();
foreach ($products as $product): 
 $proids[]= $product->getId();
endforeach; 
// print_r($proids);   
    
    
   /**
 *  Mage::registry('current_category')->getId();
 *     $entity_ids = $entity_ids = array(4497,4498,4499);

 * $reviewcollection = Mage::getModel('review/review')->getCollection()
 *     ->addStoreFilter(Mage::app()->getStore()->getId())
 *     ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
 *     ->addFieldToFilter('entity_id', Mage_Review_Model_Review::ENTITY_PRODUCT)
 *     ->addFieldToFilter('entity_pk_value', array('in' => $entity_ids))
 *     ->setDateOrder()
 *     ->addRateVotes();


 * $_items = $reviewcollection->getItems();
 * print_r($_items);
 */
?>
</div>
</div>
<div class="review_bestselling_right">
    <?php //echo $this->getLayout()->createBlock('damir/bestsellers')->setTemplate('damir/bestsellers.phtml')->toHtml(); ?>
    
    <?php
    $categoryid = Mage::getSingleton('catalog/layer')->getCurrentCategory();
    $storeId = (int) Mage::app()->getStore()->getId();
 
        // Date
        $date = new Zend_Date();
        $toDate = $date->setDay(1)->getDate()->get('Y-MM-dd');
        $fromDate = $date->subMonth(1)->getDate()->get('Y-MM-dd');
 
        $collection = Mage::getResourceModel('catalog/product_collection')
            ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
            ->addStoreFilter()
            ->addPriceData()
            ->addCategoryFilter($categoryid)
            ->addTaxPercents()
            ->addUrlRewrite()
            ->setPageSize(5);
 
        $collection->getSelect()
            ->joinLeft(
                array('aggregation' => $collection->getResource()->getTable('sales/bestsellers_aggregated_monthly')),
                "e.entity_id = aggregation.product_id AND aggregation.store_id={$storeId} AND aggregation.period BETWEEN '{$fromDate}' AND '{$toDate}'",
                array('SUM(aggregation.qty_ordered) AS sold_quantity')
            )
            ->group('e.entity_id')
            ->order(array('sold_quantity DESC', 'e.created_at'));
 
        Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
        Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
 
    ?>
 <div class="box best-selling">
<h3><?php echo $this->__('Best Selling Products');?></h3>
<div class="best-selling-inner">
<ul>
    <?php $counter=0; foreach ($collection as $product):
     ?>
        <li>
            <a class="bprodut_image" href="<?php echo $product->getProductUrl() ?>"><img class="product-img" src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(70); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" width="70" border="0" /></a>
            <div class="product-description">
                <h4><a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->stripTags($product->getName(), null, true); ?></a></h4>
                <p>
                <?php
                    $my_product = Mage::getModel('catalog/product')->load($product->getId());
                    $short_des = substr($my_product->getShortdescription(),0,100);
                    $des = substr($my_product->getDescription(),0,100);
                    if(!empty($short_des)){
                     echo $short_des;   
                    }else {
                     echo $des;   
                    }
                ?>
                </p>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
</div>
</div>   
</div>
</div>

<div class="category_des">
 <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('category_text')->toHtml(); ?>   
</div>